name: Node.js CI

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Install playwright browsers
      run: npx playwright install --with-deps
    - uses: microsoft/playwright-github-action@v1
    - name: run CodeceptJS tests
      uses: actions/setup-node@v3  
    - name: Run Codecept tests
      run: npm run codeceptjs
    - name: Generate Allure Report
      run: npm run allure-report
      if: always()
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
    
